import Head from 'next/head'
import Link from '../components/Link'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <div className='user-brief d-flex'>
          <Image src="/images/avatar.jpg" width={60} height={60} alt="Dan Abramove" />
          <div className="d-flex flex-column align-items-start ms-2">
            <span>Personal blog by <Link href="">Dan Abramov.</Link></span>
            <span>I explain with words and code.</span>
          </div>
        </div>

        <div className="articles d-flex flex-column my-5">
          <div className="articles-title">
            <h3><Link href="/">npm audit: Broken by Design</Link></h3>
          </div>
          <div className="articles-date mb-1">
            <span>July 7, 2021 • ☕️☕️☕️ 14 min read</span>
          </div>
          <div className="articles-abstract">
            <span>Found 99 vulnerabilities (84 moderately irrelevant, 15 highly irrelevant)</span>
          </div>
        </div>

        <div className="articles d-flex flex-column my-5">
          <div className="articles-title">
            <h3><Link href="/">npm audit: Broken by Design</Link></h3>
          </div>
          <div className="articles-date mb-1">
            <span>July 7, 2021 • ☕️☕️☕️ 14 min read</span>
          </div>
          <div className="articles-abstract">
            <span>Found 99 vulnerabilities (84 moderately irrelevant, 15 highly irrelevant)</span>
          </div>
        </div>

        <div className="articles d-flex flex-column my-5">
          <div className="articles-title">
            <h3><Link href="/">npm audit: Broken by Design</Link></h3>
          </div>
          <div className="articles-date mb-1">
            <span>July 7, 2021 • ☕️☕️☕️ 14 min read</span>
          </div>
          <div className="articles-abstract">
            <span>Found 99 vulnerabilities (84 moderately irrelevant, 15 highly irrelevant)</span>
          </div>
        </div>
      </section>

    </div>
  )
}
